Fix: distutils related build failure in python 3.11, removal in 3.12
distutils.sysconfig.get_config_var('SO') was deprecated in python 3.4, and is unset in python 3.11.0.

Causes PYTHON3_SO=None -> _RNA.so builds as "_RNANone" -> build failure:
```
ImportError: cannot import name '_RNA' from partially initialized module 'RNA'
```
See: python/cpython#60958, python/cpython#63754 and [deprecation notice here](https://github.com/python/cpython/blob/dd53b79de0ea98af6a11481217a961daef4e9774/Doc/whatsnew/3.4.rst#deprecations-in-the-python-api).

Also, module [distutils](https://docs.python.org/3/library/distutils.html) is deprecated and has planned removal in 3.12.
Functions get_python_inc, get_python_lib are removed, see: python/cpython#92584.